### ISSUE TITLE
Character limitation for Pet name, owner name, address 

### ISSUE THREAD

**Issue by Dineshraj555** [AY2122S2-CS2103T-T13-1/tp#106]
<img width="1061" alt="Screenshot 2022-03-31 at 12 14 33 AM" src="https://user-images.githubusercontent.com/77185712/160882452-eefd9830-654e-4ec8-b221-d42f6d838e0a.png">

We should either consider wrapping text or indicate character limit in UG to avoid this.

**Comment by soloplxya** [comment]
I am working on this bug in another issue. Currently my implementation uses a limited textfield, does that sound ok?
