### ISSUE TITLE
[PE-D] Add command failure message does not match UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-1/tp#122]
Very minor inconsistency in the order of parameters:

![image.png](https://raw.githubusercontent.com/justinyjt/ped/main/files/7bbc2ef4-8a89-4f29-8eb9-7c6e9fd9348e.png)

vs

![image.png](https://raw.githubusercontent.com/justinyjt/ped/main/files/358f4819-35c0-480b-953b-c9236679778f.png)

where owner name is before phone number in ug but order is swapped in error message

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: justinyjt/ped#2

**Comment by tsumian** [comment]
Fix this
