### ISSUE TITLE
[PE-D] Calling edit command in a filtered list causes the app to list all pets after execution

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-1/tp#133]
Not sure if this is intended, but if I were to filter a list byDate and edit a field of a given index in the filtered list, the app will list all pets after the edit command is run.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: justinyjt/ped#4

**Comment by tsumian** [comment]
If can change then change, if not specify in UG
