### ISSUE TITLE
As a pet daycare owner, I can track the attendance of the pets.

### ISSUE THREAD

**Issue by soloplxya** [AY2122S2-CS2103T-T13-1/tp#45]

**Comment by tsumian** [comment]
Create a new command `attendance` with arguments `petID`, `date` (that pet is coming in), `pickup time` and `drop off time`.
Ensure that format for DD/MM/YYYY is correct by throwing exception and error message.
Generate a new file for each pet with the ID as name of file. Chunk all the fixed attributes to the top of the file

**ID.txt**
Peepee
91234567
John Tan
Computing drive....
Diet
DD/MM/YYYY HHMM HHMM
DD/MM/YYYY HHMM HHMM
.
.
.
DD/MM/YYYY HHMM HHMM

**Comment by tsumian** [comment]
Linked with 'time' command. Edit 'time' command to include another argument 'date'. Update UserGuide to include 'track' command, remove 'owner' and 'food' commands.

**Comment by Dineshraj555** [comment]
split tasks:

1. Creation of pet index file upon adding a pet. File naming format: _[(pet name without space) + (phone_number].txt_
2. Attendance command `add i/index d/ddmmyyyy p/HHMM d/HHMM `
