### ISSUE TITLE
Cannot view full diet on CLI

### ISSUE THREAD

**Issue by soloplxya** [AY2122S2-CS2103T-T13-1/tp#83]
Diet gets truncated if too long.  Need to soft-wrap the excess to the next line. 
![image](https://user-images.githubusercontent.com/69782911/159837300-b78da97e-3556-4dc1-a9df-be50c1574031.png)

**Comment by tobihy** [comment]
Possible solution may be to set a hard limit for length of string inputs for diet and similar commands/fields? So that such bugs will not occur for all variable length fields.
